/**
 * Grupo Aval Acciones y Valores S.A. CONFIDENTIAL
 *
 * <p>Copyright (c) 2018 . All Rights Reserved.
 *
 * <p>NOTICE: This file is subject to the terms and conditions defined in file 'LICENSE', which is
 * part of this source code package.
 */
package co.com.avvillaspasivos.util;

import co.com.avvillaspasivos.model.BodyGetPdf;
import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;

import java.util.Map;

public class Constantes {

  private Constantes() {
    throw new IllegalStateException("Utility class");
  }

  public static final String EXECUTION_TAGS = "@regresion";
  public static final String RUTA_STEPS_DEFINITIONS = "co.com.avvillaspasivos.stepsdefinitions";
  public static final String TEXT_MODAL_VER_MAS = "Conoce los beneficios que tenemos para ti";
  public static final String TEXTO_ERROR_PROCESO_PRINCIPAL =
      "Lo sentimos, no podemos continuar con tu solicitud";
  public static final String TEXTO_ERROR_PROCESO_SECUNDARIO =
      "Debes acercarte a una oficina AV Villas para abrir tu cuenta.";
  public static final String PATH_FORM_IDENTIFICACION = "user-identification";
  public static final String PATH_OFRECIMIENTO = "account-selection";
  public static final int MAX_WAIT = 60;
  public static final int MAX_WAIT_GET_PDF = 120;
  public static final int DB_WAIT = 3;
  public static final String TEXTO_SUPERIOR_LIMITE_TAMANIO = "sssssqqqqqwwwwweeeeeqqqqq";
  public static final String EXCEED_SIZE_SALARY_TEXT = "12345678901";
  public static final String TEST_DIRECTION = "Direccion de prueba pasivo avvillas";
  public static final int SALARY_SIZE = 10;
  public static final String TAG_OTP = "s1:CustIdNum";
  public static final String VALUE_OTP = "12345678";
  public static final String STG_VALUE = "stg";
  public static final String DEV_VALUE = "dev";
  public static final String DOMINA = "DOMINA";
  public static final String FULL_CITIES = "FULL";
  public static final String DATA_CLIENT_PROP = "client";
  public static final String DATA_UPDATED_PROP = "updated";
  public static final String DATA_CHANNELS_PROP = "hasChannels";
  public static final String DATA_CAT_PROP = "cat";
  public static final String DATA_OTP_PROP = "validOtp";
  public static final String DATA_REST_LIST_PROP = "restrictiveList";
  public static final String DATA_FUNDING_ACC = "fundingAcc";
  public static final String DATA_FUNDING_ACC_VALLUE = "fundingAccValue";
  public static final String DATA_BLOCK_PROP = "block";
  public static final String DATA_USERS_PROP = "users";
  public static final String DATA_NUMDOC_PROP = "numDoc";
  public static final String DATA_TIPODOC_PROP = "tipoDoc";
  public static final String DATA_FIRST_NAME_PROP = "firstName";
  public static final String DATA_LAST_NAME_PROP = "lastName";
  public static final String DATA_PHONE_PROP = "phone";
  public static final String DATA_SALARY_PROP = "salary";
  public static final String VALID_SALARY = "10000";
  public static final String TAG_VALID = "VALID";
  public static final String TAG_EXCEED_MAX = "EXCEED";
  public static final String INVALID_SALARY = "9999";
  public static final String TAG_INVALID = "INVALID";
  public static final String PRO_SALARY = "1800000";
  public static final String TAG_PRO = "PRO";
  public static final String SIMPLE_SALARY = "1799000";
  public static final String TAG_SIMPLE = "SIMPLE";
  public static final String TAG_SIMPLE_ACCOUNT = "cuenta simple";
  public static final String TAG_ACCEPT = "acepta";
  public static final String TAG_NOT_ACCEPT = "no acepta";
  public static final String TAG_CONFIRM = "confirma";
  public static final String TAG_NOT_CONFIRM = "no confirma";
  public static final String TAG_EDIT = "modifica";
  public static final String TAG_NOT_EDIT = "no modifica";
  public static final String TRUE_VALUE = "verdadero";
  public static final String FALSE_VALUE = "falso";
  public static final String CLIENT_UPDATED_FUNDING_ACC_WITHOUT_CHANNELS_RENEWAL =
      "cliente actualizado con cuenta para fondeo no enrolado con renovacion";
 public static final String CLIENT_FUNDING_ACC =
      "con cuentas en el banco y saldo de 36'000.000";
 public static final String CLIENT_WiTH_OUT_FUNDING_ACC =
      "sin cuentas en el banco";
  public static final String CLIENT_UPDATED_FUNDING_ACC_WITH_CHANNELS_NO_RENEWAL =
      "cliente actualizado con cuenta para fondeo enrolado sin renovacion";
  public static final String CLIENT_UPDATED_REST_LIST_CAT_WITH_CHANNELS =
      "cliente actualizado sin lista restrictiva con cuenta cat y que tenga canales";
  public static final String CLIENT_UPDATED_REST_LIST_NOT_CAT_WITH_CHANNELS =
      "cliente actualizado sin lista restrictiva sin cuenta cat y que tenga canales";
  public static final String CLIENT_UPDATED_WITHOUT_CHANNELS =
      "cliente actualizado que no tenga canales";
  public static final String CLIENT_WITHOUT_CHANNELS =
      "cliente sin canales";
  public static final String CLIENT_WITH_CHANNELS =
      "cliente con canales";
  public static final String CLIENT_UPDATED_WITH_CHANNELS =
      "cliente actualizado con canales activos";
  public static final String CLIENT_UPDATED = "cliente actualizado";
  public static final String NO_CLIENT_NO_UPDATED_WITHOUT_CHANNELS =
      "no cliente no actualizado que no tenga canales";
  public static final String CLIENT_NO_UPDATED = "cliente no actualizado";
  public static final String RESUMEN_TITLE_XPATH = "//h2";
  public static final String ACCOUNT_NUMBER_CLASS = "account-number";
  public static final String MONEY_CLASS = "money";
  public static final String MONTH_COST_VALUE = "$ 0,00";
  public static final String WITHDRAWALS_TEXT = "3 retiros gratis al mes";
  public static final String INSURANCE_COST = "$ 14.800,00";
  public static final String CORRECT_PASS_OPTION = "correcta";
  public static final String CORRECT_PASS = "1636";
  public static final String PRODUCT_CDT = "CDT";
  public static final String PRODUCT_CDA = "CDA";
  public static final String AUTHENTICATION_ACTOR = "Actor autenticación";
  public static final String BANK_LIST_ACTOR = "Actor ws bank list";
  public static final String CRM_ACTOR = "Actor ws crm";
  public static final String MAIN_ACTOR = "Actor principal";
  public static final String ACCT_COD_TYPE_GET_PDF = "CUENTA_PRO";
  public static final String NO_SELECTED_ACCOUNT_GET_PDF = "NOT_SELECTED";
  public static final String ACCOUNT_FUNDING_TAG = "Cuenta AV Villas";
  public static final String ACCOUNT_PROFIT_TAG = "Cuenta AV Villas";
  public static final String NEW_ACCOUNT_PROFIT_TAG = "Nueva Cuenta AV Villas";
  public static final String EXPIRATION_TAG = "al vencimiento";
  public static final String EMPLOYMENT_VALUE = "empleado";
  public static final String RETIRED_VALUE = "pensionado";
  public static final String STUDENT_VALUE = "estudiante";
  public static final String HOME_VALUE = "hogar";
  public static final String INDEPENDENT_VALUE = "independiente";
  public static final String INDEPENDENT_BUSINESS_VALUE = "independiente con negocio";


  public static final Map<String, String> UI_URL_PATHS =
      ImmutableMap.<String, String>builder()
          .put("tips CDT", "tips-ahorro")
          .put("PSE en el flujo", "pse")
          .put("resumen", "resumen-producto")
          .put("PSE externa", "https://registro.desarrollo.pse.com.co/")
          .build();

  public static final Map<String, String> MAP_URL_PATHS =
      ImmutableMap.<String, String>builder()
          .put("enrolamiento de canales", "enrolamiento-cliente")
          .put("tips de ahorro", "tips-ahorro")
          .build();

  public static final Map<String, String> pdfCodeExpectedMap =
      ImmutableMap.<String, String>builder()
          .put("fondeo por PSE, no seleccionó cuenta y no requiere formato declarante", "1508")
          .put("fondeo por PSE, no seleccionó cuenta y requiere formato declarante", "1509")
          .put(
              "fondeo por PSE, con cuenta abierta en el flujo y no requiere formato declarante",
              "1510")
          .put(
              "fondeo por PSE, con cuenta abierta en el flujo y requiere formato declarante",
              "1511")
          .put("fondeo con debito de cuenta en el banco y no requiere formato declarante", "1512")
          .put("fondeo con debito de cuenta en el banco y requiere formato declarante", "1513")
          .build();

  public static final Map<String, BodyGetPdf> pdfOptionsMap =
      ImmutableMap.<String, BodyGetPdf>builder()
          .put(
              "fondeo por PSE, no seleccionó cuenta y no requiere formato declarante",
              BodyGetPdf.builder()
                  .acctCodType(ACCT_COD_TYPE_GET_PDF)
                  .selectInsurance(false)
                  .notDeclarantDocument(false)
                  .fundingType("PSE")
                  .selectedAccount(NO_SELECTED_ACCOUNT_GET_PDF)
                  .build())
          .put(
              "fondeo por PSE, no seleccionó cuenta y requiere formato declarante",
              BodyGetPdf.builder()
                  .acctCodType(ACCT_COD_TYPE_GET_PDF)
                  .selectInsurance(false)
                  .notDeclarantDocument(true)
                  .fundingType("PSE")
                  .selectedAccount(NO_SELECTED_ACCOUNT_GET_PDF)
                  .build())
          .put(
              "fondeo por PSE, con cuenta abierta en el flujo y no requiere formato declarante",
              BodyGetPdf.builder()
                  .acctCodType(ACCT_COD_TYPE_GET_PDF)
                  .selectInsurance(false)
                  .notDeclarantDocument(false)
                  .fundingType("PSE")
                  .selectedAccount("FLOW_ACCOUNT")
                  .build())
          .put(
              "fondeo por PSE, con cuenta abierta en el flujo y requiere formato declarante",
              BodyGetPdf.builder()
                  .acctCodType(ACCT_COD_TYPE_GET_PDF)
                  .selectInsurance(false)
                  .notDeclarantDocument(true)
                  .fundingType("PSE")
                  .selectedAccount("FLOW_ACCOUNT")
                  .build())
          .put(
              "fondeo con debito de cuenta en el banco y no requiere formato declarante",
              BodyGetPdf.builder()
                  .acctCodType(ACCT_COD_TYPE_GET_PDF)
                  .selectInsurance(true)
                  .notDeclarantDocument(false)
                  .fundingType("BANK_DEBIT")
                  .selectedAccount(NO_SELECTED_ACCOUNT_GET_PDF)
                  .build())
          .put(
              "fondeo con debito de cuenta en el banco y requiere formato declarante",
              BodyGetPdf.builder()
                  .acctCodType(ACCT_COD_TYPE_GET_PDF)
                  .selectInsurance(true)
                  .notDeclarantDocument(true)
                  .fundingType("BANK_DEBIT")
                  .selectedAccount(NO_SELECTED_ACCOUNT_GET_PDF)
                  .build())
          .build();

  public static final ImmutableList<String> LIST_CITIES =
      ImmutableList.of(
          "Acacías - Meta",
          "Aguazul - Casanare",
          "Andalucía - Valle Del Cauca",
          "Apartadó - Antioquia",
          "Armenia - Quindío",
          "Barbosa - Antioquia",
          "Barrancabermeja - Santander",
          "Barranquilla - Atlántico",
          "Bello - Antioquia",
          "Bogotá D.C. - Bogotá D.C.",
          "Bucaramanga - Santander",
          "Buenaventura - Valle Del Cauca",
          "Bugalagrande - Valle Del Cauca",
          "Cajicá - Cundinamarca",
          "Calarcá - Quindío",
          "Caldas - Antioquia",
          "Cali - Valle Del Cauca",
          "Candelaria - Valle Del Cauca",
          "Carepa - Antioquia",
          "Cartagena - Bolívar",
          "Cartago - Valle Del Cauca",
          "Caucasia - Antioquia",
          "Chigorodó - Antioquia",
          "Chinú - Córdoba",
          "Chía - Cundinamarca",
          "Ciénaga - Magdalena",
          "Cogua - Cundinamarca",
          "Copacabana - Antioquia",
          "Cota - Cundinamarca",
          "Cúcuta - Norte De Santander",
          "Dosquebradas - Risaralda",
          "Duitama - Boyacá",
          "El Carmen de Viboral - Antioquia",
          "El Rosal - Cundinamarca",
          "El Santuario - Antioquia",
          "Envigado - Antioquia",
          "Facatativá - Cundinamarca",
          "Florencia - Caquetá",
          "Florida - Valle Del Cauca",
          "Floridablanca - Santander",
          "Funza - Cundinamarca",
          "Fusagasugá - Cundinamarca",
          "Gachancipá - Cundinamarca",
          "Garzón - Huila",
          "Girardota - Antioquia",
          "Girón - Santander",
          "Guadalajara de buga - Valle Del Cauca",
          "Guarne - Antioquia",
          "Guatapé - Antioquia",
          "Ibagué - Tolima",
          "Ipiales - Nariño",
          "Istmina - Chocó",
          "Itagüí - Antioquia",
          "Jamundí - Valle Del Cauca",
          "La Calera - Cundinamarca",
          "La Ceja - Antioquia",
          "La Dorada - Caldas",
          "La Estrella - Antioquia",
          "La Unión - Antioquia",
          "La Unión - Valle Del Cauca",
          "La Victoria - Valle Del Cauca",
          "Las Palmas - Antioquia",
          "Lebrija - Santander",
          "Los Patios - Norte De Santander",
          "Madrid - Cundinamarca",
          "Manizales - Caldas",
          "Marinilla - Antioquia",
          "Medellín - Antioquia",
          "Montelíbano - Córdoba",
          "Montería - Córdoba",
          "Mosquera - Cundinamarca",
          "Neiva - Huila",
          "Nobsa - Boyacá",
          "Paipa - Boyacá",
          "Palmira - Valle Del Cauca",
          "Pasto - Nariño",
          "Pereira - Risaralda",
          "Peñol - Antioquia",
          "Piedecuesta - Santander",
          "Pitalito - Huila",
          "Popayán - Cauca",
          "Pradera - Valle Del Cauca",
          "Puerto Berrío - Antioquia",
          "Puerto Colombia - Atlántico",
          "Puerto Salgar - Cundinamarca",
          "Quibdó - Chocó",
          "Retiro - Antioquia",
          "Rionegro - Antioquia",
          "Roldanillo - Valle Del Cauca",
          "Sabaneta - Antioquia",
          "Sahagún - Córdoba",
          "Sampués - Sucre",
          "San Antonio - Antioquia",
          "San Gil - Santander",
          "Santa Elena - Antioquia",
          "Santa Marta - Magdalena",
          "Sincelejo - Sucre",
          "Soacha - Cundinamarca",
          "Sogamoso - Boyacá",
          "Soledad - Atlántico",
          "Sopó - Cundinamarca",
          "Subachoque - Cundinamarca",
          "Tabio - Cundinamarca",
          "Tenjo - Cundinamarca",
          "Tibasosa - Boyacá",
          "Timaná - Huila",
          "Tocancipá - Cundinamarca",
          "Tuluá - Valle Del Cauca",
          "Tunja - Boyacá",
          "Turbaco - Bolívar",
          "Turbo - Antioquia",
          "Valledupar - Cesar",
          "Villa del Rosario - Norte De Santander",
          "Villamaría - Caldas",
          "Villavicencio - Meta",
          "Yopal - Casanare",
          "Yumbo - Valle Del Cauca",
          "Zarzal - Valle Del Cauca",
          "Zipaquirá - Cundinamarca");

  public static final ImmutableList<String> LIST_CITIES_FULL =
      ImmutableList.of(
          "Abejorral - Antioquia",
          "Abrego - Norte de Santander",
          "Abriaquí - Antioquia",
          "Acacias - Meta",
          "Acandí - Chocó",
          "Acevedo - Huila",
          "Achí - Bolívar",
          "Agrado - Huila",
          "Agua de Dios - Cundinamarca",
          "Aguachica - Cesar",
          "Aguada - Santander",
          "Aguadas - Caldas",
          "Aguazul - Casanare",
          "Agustín Codazzi - Cesar",
          "Aipe - Huila",
          "Albania - Caquetá",
          "Albania - La Guajira",
          "Albania - Santander",
          "Albán - Cundinamarca",
          "Albán - Nariño",
          "Alcalá - Valle del Cauca",
          "Aldana - Nariño",
          "Alejandría - Antioquia",
          "Algarrobo - Magdalena",
          "Algeciras - Huila",
          "Almaguer - Cauca",
          "Almeida - Boyacá",
          "Alpujarra - Tolima",
          "Altamira - Huila",
          "Alto Baudo - Chocó",
          "Altos del Rosario - Bolívar",
          "Alvarado - Tolima",
          "Amagá - Antioquia",
          "Amalfi - Antioquia",
          "Ambalema - Tolima",
          "Anapoima - Cundinamarca",
          "Ancuyá - Nariño",
          "Andalucía - Valle del Cauca",
          "Andes - Antioquia",
          "Angelópolis - Antioquia",
          "Angostura - Antioquia",
          "Anolaima - Cundinamarca",
          "Anorí - Antioquia",
          "Anserma - Caldas",
          "Ansermanuevo - Valle del Cauca",
          "Anza - Antioquia",
          "Anzoátegui - Tolima",
          "Apartadó - Antioquia",
          "Apulo - Cundinamarca",
          "Apía - Risaralda",
          "Aquitania - Boyacá",
          "Aracataca - Magdalena",
          "Aranzazu - Caldas",
          "Aratoca - Santander",
          "Arauca - Arauca",
          "Arauquita - Arauca",
          "Arbeláez - Cundinamarca",
          "Arboleda - Nariño",
          "Arboledas - Norte de Santander",
          "Arboletes - Antioquia",
          "Arcabuco - Boyacá",
          "Archipiélago de San Andrés Providencia y Santa Catalina - Providencia",
          "Arenal - Bolívar",
          "Argelia - Antioquia",
          "Argelia - Cauca",
          "Argelia - Valle del Cauca",
          "Ariguaní - Magdalena",
          "Arjona - Bolívar",
          "Armenia - Antioquia",
          "Armenia - Quindío",
          "Armero - Tolima",
          "Arroyohondo - Bolívar",
          "Astrea - Cesar",
          "Ataco - Tolima",
          "Atrato - Chocó",
          "Ayapel - Córdoba",
          "Bagadó - Chocó",
          "Bahía Solano - Chocó",
          "Bajo Baudó - Chocó",
          "Balboa - Cauca",
          "Balboa - Risaralda",
          "Baranoa - Atlántico",
          "Baraya - Huila",
          "Barbacoas - Nariño",
          "Barbosa - Antioquia",
          "Barbosa - Santander",
          "Barichara - Santander",
          "Barranca de Upía - Meta",
          "Barrancabermeja - Santander",
          "Barrancas - La Guajira",
          "Barranco de Loba - Bolívar",
          "Barranco Minas - Guainía",
          "Barranquilla - Atlántico",
          "Becerril - Cesar",
          "Belalcázar - Caldas",
          "Bello - Antioquia",
          "Belmira - Antioquia",
          "Beltrán - Cundinamarca",
          "Belén - Boyacá",
          "Belén - Nariño",
          "Belén de Bajira - Chocó",
          "Belén de Los Andaquies - Caquetá",
          "Belén de Umbría - Risaralda",
          "Berbeo - Boyacá",
          "Betania - Antioquia",
          "Betulia - Antioquia",
          "Betulia - Santander",
          "Betéitiva - Boyacá",
          "Bituima - Cundinamarca",
          "Boavita - Boyacá",
          "Bochalema - Norte de Santander",
          "Bogotá D.C. - Bogotá D.C.",
          "Bojacá - Cundinamarca",
          "Bojaya - Chocó",
          "Bolívar - Cauca",
          "Bolívar - Santander",
          "Bolívar - Valle del Cauca",
          "Bosconia - Cesar",
          "Boyacá - Boyacá",
          "Briceño - Antioquia",
          "Briceño - Boyacá",
          "Bucaramanga - Santander",
          "Bucarasica - Norte de Santander",
          "Buena Vista - Boyacá",
          "Buenaventura - Valle del Cauca",
          "Buenavista - Córdoba",
          "Buenavista - Quindío",
          "Buenavista - Sucre",
          "Buenos Aires - Cauca",
          "Buesaco - Nariño",
          "Bugalagrande - Valle del Cauca",
          "Buriticá - Antioquia",
          "Busbanzá - Boyacá",
          "Cabrera - Cundinamarca",
          "Cabrera - Santander",
          "Cabuyaro - Meta",
          "Cacahual - Guainía",
          "Cachipay - Cundinamarca",
          "Cachirá - Norte de Santander",
          "Caicedo - Antioquia",
          "Caicedonia - Valle del Cauca",
          "Caimito - Sucre",
          "Cajamarca - Tolima",
          "Cajibío - Cauca",
          "Cajicá - Cundinamarca",
          "Calamar - Bolívar",
          "Calamar - Guaviare",
          "Calarcá - Quindío",
          "Caldas - Antioquia",
          "Caldas - Boyacá",
          "Caldono - Cauca",
          "Cali - Valle del Cauca",
          "California - Santander",
          "Calima - Valle del Cauca",
          "Caloto - Cauca",
          "Campamento - Antioquia",
          "Campo de la Cruz - Atlántico",
          "Campoalegre - Huila",
          "Campohermoso - Boyacá",
          "Canalete - Córdoba",
          "Candelaria - Atlántico",
          "Candelaria - Valle del Cauca",
          "Cantagallo - Bolívar",
          "Caparrapí - Cundinamarca",
          "Capitanejo - Santander",
          "Caqueza - Cundinamarca",
          "Caracolí - Antioquia",
          "Caramanta - Antioquia",
          "Carcasí - Santander",
          "Carepa - Antioquia",
          "Carmen de Apicala - Tolima",
          "Carmen de Carupa - Cundinamarca",
          "Carmen del Darien - Chocó",
          "Carolina - Antioquia",
          "Cartagena - Bolívar",
          "Cartagena del Chairá - Caquetá",
          "Cartago - Valle del Cauca",
          "Caruru - Vaupés",
          "Casabianca - Tolima",
          "Castilla la Nueva - Meta",
          "Caucasia - Antioquia",
          "Cañasgordas - Antioquia",
          "Cepitá - Santander",
          "Cereté - Córdoba",
          "Cerinza - Boyacá",
          "Cerrito - Santander",
          "Cerro San Antonio - Magdalena",
          "Chachagüí - Nariño",
          "Chaguaní - Cundinamarca",
          "Chalán - Sucre",
          "Chaparral - Tolima",
          "Charalá - Santander",
          "Charta - Santander",
          "Chigorodó - Antioquia",
          "Chimichagua - Cesar",
          "Chimá - Córdoba",
          "Chimá - Santander",
          "Chinavita - Boyacá",
          "Chinchiná - Caldas",
          "Chinácota - Norte de Santander",
          "Chinú - Córdoba",
          "Chipaque - Cundinamarca",
          "Chipatá - Santander",
          "Chiquinquirá - Boyacá",
          "Chiriguaná - Cesar",
          "Chiscas - Boyacá",
          "Chita - Boyacá",
          "Chitagá - Norte de Santander",
          "Chitaraque - Boyacá",
          "Chivatá - Boyacá",
          "Chivolo - Magdalena",
          "Chivor - Boyacá",
          "Choachí - Cundinamarca",
          "Chocontá - Cundinamarca",
          "Chámeza - Casanare",
          "Chía - Cundinamarca",
          "Chíquiza - Boyacá",
          "Cicuco - Bolívar",
          "Cimitarra - Santander",
          "Circasia - Quindío",
          "Cisneros - Antioquia",
          "Ciudad Bolívar - Antioquia",
          "Ciénaga - Magdalena",
          "Ciénaga de Oro - Córdoba",
          "Ciénega - Boyacá",
          "Clemencia - Bolívar",
          "Cocorná - Antioquia",
          "Coello - Tolima",
          "Cogua - Cundinamarca",
          "Colombia - Huila",
          "Coloso - Sucre",
          "Colón - Nariño",
          "Colón - Putumayo",
          "Concepción - Antioquia",
          "Concepción - Santander",
          "Concordia - Antioquia",
          "Concordia - Magdalena",
          "Condoto - Chocó",
          "Confines - Santander",
          "Consaca - Nariño",
          "Contadero - Nariño",
          "Contratación - Santander",
          "Convención - Norte de Santander",
          "Copacabana - Antioquia",
          "Coper - Boyacá",
          "Corinto - Cauca",
          "Coromoro - Santander",
          "Corozal - Sucre",
          "Corrales - Boyacá",
          "Cota - Cundinamarca",
          "Cotorra - Córdoba",
          "Covarachía - Boyacá",
          "Coveñas - Sucre",
          "Coyaima - Tolima",
          "Cravo Norte - Arauca",
          "Cuaspud - Nariño",
          "Cubarral - Meta",
          "Cubará - Boyacá",
          "Cucaita - Boyacá",
          "Cucunubá - Cundinamarca",
          "Cucutilla - Norte de Santander",
          "Cumaral - Meta",
          "Cumaribo - Vichada",
          "Cumbal - Nariño",
          "Cumbitara - Nariño",
          "Cunday - Tolima",
          "Curillo - Caquetá",
          "Curití - Santander",
          "Curumaní - Cesar",
          "Cuítiva - Boyacá",
          "Cáceres - Antioquia",
          "Cácota - Norte de Santander",
          "Cértegui - Chocó",
          "Cómbita - Boyacá",
          "Córdoba - Bolívar",
          "Córdoba - Nariño",
          "Córdoba - Quindío",
          "Cúcuta - Norte de Santander",
          "Dabeiba - Antioquia",
          "Dagua - Valle del Cauca",
          "Dibula - La Guajira",
          "Distracción - La Guajira",
          "Dolores - Tolima",
          "Don Matías - Antioquia",
          "Dosquebradas - Risaralda",
          "Duitama - Boyacá",
          "Durania - Norte de Santander",
          "Ebéjico - Antioquia",
          "El Bagre - Antioquia",
          "El Banco - Magdalena",
          "El Cairo - Valle del Cauca",
          "El Calvario - Meta",
          "El Cantón del San Pablo - Chocó",
          "El Carmen - Norte de Santander",
          "El Carmen de Atrato - Chocó",
          "El Carmen de Bolívar - Bolívar",
          "El Carmen de Chucurí - Santander",
          "El Carmen de Viboral - Antioquia",
          "El Castillo - Meta",
          "El Cerrito - Valle del Cauca",
          "El Charco - Nariño",
          "El Cocuy - Boyacá",
          "El Colegio - Cundinamarca",
          "El Copey - Cesar",
          "El Doncello - Caquetá",
          "El Dorado - Meta",
          "El Dovio - Valle del Cauca",
          "El Encanto - Amazonas",
          "El Espino - Boyacá",
          "El Guacamayo - Santander",
          "El Guamo - Bolívar",
          "El Litoral del San Juan - Chocó",
          "El Molino - La Guajira",
          "El Paso - Cesar",
          "El Paujil - Caquetá",
          "El Peñol - Nariño",
          "El Peñón - Bolívar",
          "El Peñón - Cundinamarca",
          "El Peñón - Santander",
          "El Piñon - Magdalena",
          "El Playón - Santander",
          "El Retorno - Guaviare",
          "El Retén - Magdalena",
          "El Roble - Sucre",
          "El Rosal - Cundinamarca",
          "El Rosario - Nariño",
          "El Santuario - Antioquia",
          "El Tablón de Gómez - Nariño",
          "El Tambo - Cauca",
          "El Tambo - Nariño",
          "El Tarra - Norte de Santander",
          "El Zulia - Norte de Santander",
          "El Águila - Valle del Cauca",
          "Elías - Huila",
          "Encino - Santander",
          "Enciso - Santander",
          "Entrerrios - Antioquia",
          "Envigado - Antioquia",
          "Espinal - Tolima",
          "Facatativá - Cundinamarca",
          "Falan - Tolima",
          "Filadelfia - Caldas",
          "Filandia - Quindío",
          "Firavitoba - Boyacá",
          "Flandes - Tolima",
          "Florencia - Caquetá",
          "Florencia - Cauca",
          "Floresta - Boyacá",
          "Florida - Valle del Cauca",
          "Floridablanca - Santander",
          "Florián - Santander",
          "Fomeque - Cundinamarca",
          "Fonseca - La Guajira",
          "Fortul - Arauca",
          "Fosca - Cundinamarca",
          "Francisco Pizarro - Nariño",
          "Fredonia - Antioquia",
          "Fresno - Tolima",
          "Frontino - Antioquia",
          "Fuente de Oro - Meta",
          "Fundación - Magdalena",
          "Funes - Nariño",
          "Funza - Cundinamarca",
          "Fusagasugá - Cundinamarca",
          "Fúquene - Cundinamarca",
          "Gachala - Cundinamarca",
          "Gachancipá - Cundinamarca",
          "Gachantivá - Boyacá",
          "Gachetá - Cundinamarca",
          "Galapa - Atlántico",
          "Galeras - Sucre",
          "Galán - Santander",
          "Gama - Cundinamarca",
          "Gamarra - Cesar",
          "Gambita - Santander",
          "Gameza - Boyacá",
          "Garagoa - Boyacá",
          "Garzón - Huila",
          "Gigante - Huila",
          "Ginebra - Valle del Cauca",
          "Giraldo - Antioquia",
          "Girardot - Cundinamarca",
          "Girardota - Antioquia",
          "Girón - Santander",
          "González - Cesar",
          "Gramalote - Norte de Santander",
          "Granada - Antioquia",
          "Granada - Cundinamarca",
          "Granada - Meta",
          "Guaca - Santander",
          "Guacamayas - Boyacá",
          "Guacarí - Valle del Cauca",
          "Guachené - Cauca",
          "Guachetá - Cundinamarca",
          "Guachucal - Nariño",
          "Guadalajara de Buga - Valle del Cauca",
          "Guadalupe - Antioquia",
          "Guadalupe - Huila",
          "Guadalupe - Santander",
          "Guaduas - Cundinamarca",
          "Guaitarilla - Nariño",
          "Gualmatán - Nariño",
          "Guamal - Magdalena",
          "Guamal - Meta",
          "Guamo - Tolima",
          "Guapi - Cauca",
          "Guapotá - Santander",
          "Guaranda - Sucre",
          "Guarne - Antioquia",
          "Guasca - Cundinamarca",
          "Guatapé - Antioquia",
          "Guataquí - Cundinamarca",
          "Guatavita - Cundinamarca",
          "Guateque - Boyacá",
          "Guavatá - Santander",
          "Guayabal de Siquima - Cundinamarca",
          "Guayabetal - Cundinamarca",
          "Guayatá - Boyacá",
          "Gutiérrez - Cundinamarca",
          "Guática - Risaralda",
          "Génova - Quindío",
          "Gómez Plata - Antioquia",
          "Güepsa - Santander",
          "Güicán - Boyacá",
          "Hacarí - Norte de Santander",
          "Hatillo de Loba - Bolívar",
          "Hato - Santander",
          "Hato Corozal - Casanare",
          "Hatonuevo - La Guajira",
          "Heliconia - Antioquia",
          "Herrán - Norte de Santander",
          "Herveo - Tolima",
          "Hispania - Antioquia",
          "Hobo - Huila",
          "Honda - Tolima",
          "Ibagué - Tolima",
          "Icononzo - Tolima",
          "Iles - Nariño",
          "Imués - Nariño",
          "Inzá - Cauca",
          "Inírida - Guainía",
          "Ipiales - Nariño",
          "Iquira - Huila",
          "Isnos - Huila",
          "Istmina - Chocó",
          "Itagui - Antioquia",
          "Ituango - Antioquia",
          "Iza - Boyacá",
          "Jambaló - Cauca",
          "Jamundí - Valle del Cauca",
          "Jardín - Antioquia",
          "Jenesano - Boyacá",
          "Jericó - Antioquia",
          "Jericó - Boyacá",
          "Jerusalén - Cundinamarca",
          "Jesús María - Santander",
          "Jordán - Santander",
          "Juan de Acosta - Atlántico",
          "Junín - Cundinamarca",
          "Juradó - Chocó",
          "La Apartada - Córdoba",
          "La Argentina - Huila",
          "La Belleza - Santander",
          "La Calera - Cundinamarca",
          "La Capilla - Boyacá",
          "La Ceja - Antioquia",
          "La Celia - Risaralda",
          "La Chorrera - Amazonas",
          "La Cruz - Nariño",
          "La Cumbre - Valle del Cauca",
          "La Dorada - Caldas",
          "La Esperanza - Norte de Santander",
          "La Estrella - Antioquia",
          "La Florida - Nariño",
          "La Gloria - Cesar",
          "La Guadalupe - Guainía",
          "La Jagua de Ibirico - Cesar",
          "La Jagua del Pilar - La Guajira",
          "La Llanada - Nariño",
          "La Macarena - Meta",
          "La Merced - Caldas",
          "La Mesa - Cundinamarca",
          "La Montañita - Caquetá",
          "La Palma - Cundinamarca",
          "La Paz - Cesar",
          "La Paz - Santander",
          "La Pedrera - Amazonas",
          "La Peña - Cundinamarca",
          "La Pintada - Antioquia",
          "La Plata - Huila",
          "La Playa - Norte de Santander",
          "La Primavera - Vichada",
          "La Salina - Casanare",
          "La Sierra - Cauca",
          "La Tebaida - Quindío",
          "La Tola - Nariño",
          "La Unión - Antioquia",
          "La Unión - Nariño",
          "La Unión - Sucre",
          "La Unión - Valle del Cauca",
          "La Uvita - Boyacá",
          "La Vega - Cauca",
          "La Vega - Cundinamarca",
          "La Victoria - Amazonas",
          "La Victoria - Boyacá",
          "La Victoria - Valle del Cauca",
          "La Virginia - Risaralda",
          "Labateca - Norte de Santander",
          "Labranzagrande - Boyacá",
          "Landázuri - Santander",
          "Lebríja - Santander",
          "Leguízamo - Putumayo",
          "Leiva - Nariño",
          "Lejanías - Meta",
          "Lenguazaque - Cundinamarca",
          "Leticia - Amazonas",
          "Liborina - Antioquia",
          "Linares - Nariño",
          "Lloró - Chocó",
          "Lorica - Córdoba",
          "Los Andes - Nariño",
          "Los Córdobas - Córdoba",
          "Los Palmitos - Sucre",
          "Los Patios - Norte de Santander",
          "Los Santos - Santander",
          "Lourdes - Norte de Santander",
          "Luruaco - Atlántico",
          "Lérida - Tolima",
          "Líbano - Tolima",
          "López - Cauca",
          "Macanal - Boyacá",
          "Macaravita - Santander",
          "Maceo - Antioquia",
          "Macheta - Cundinamarca",
          "Madrid - Cundinamarca",
          "Magangué - Bolívar",
          "Magüí - Nariño",
          "Mahates - Bolívar",
          "Maicao - La Guajira",
          "Majagual - Sucre",
          "Malambo - Atlántico",
          "Mallama - Nariño",
          "Manatí - Atlántico",
          "Manaure - Cesar",
          "Manaure - La Guajira",
          "Manizales - Caldas",
          "Manta - Cundinamarca",
          "Manzanares - Caldas",
          "Maní - Casanare",
          "Mapiripana - Guainía",
          "Mapiripán - Meta",
          "Margarita - Bolívar",
          "Marinilla - Antioquia",
          "Maripí - Boyacá",
          "Mariquita - Tolima",
          "Marmato - Caldas",
          "Marquetalia - Caldas",
          "Marsella - Risaralda",
          "Marulanda - Caldas",
          "María la Baja - Bolívar",
          "Matanza - Santander",
          "Medellín - Antioquia",
          "Medina - Cundinamarca",
          "Medio Atrato - Chocó",
          "Medio Baudó - Chocó",
          "Medio San Juan - Chocó",
          "Melgar - Tolima",
          "Mercaderes - Cauca",
          "Mesetas - Meta",
          "Milán - Caquetá",
          "Miraflores - Boyacá",
          "Miraflores - Guaviare",
          "Miranda - Cauca",
          "Miriti Paraná - Amazonas",
          "Mistrató - Risaralda",
          "Mitú - Vaupés",
          "Mocoa - Putumayo",
          "Mogotes - Santander",
          "Molagavita - Santander",
          "Momil - Córdoba",
          "Mompós - Bolívar",
          "Mongua - Boyacá",
          "Monguí - Boyacá",
          "Moniquirá - Boyacá",
          "Montebello - Antioquia",
          "Montecristo - Bolívar",
          "Montelíbano - Córdoba",
          "Montenegro - Quindío",
          "Monterrey - Casanare",
          "Montería - Córdoba",
          "Morales - Bolívar",
          "Morales - Cauca",
          "Morelia - Caquetá",
          "Morichal - Guainía",
          "Morroa - Sucre",
          "Mosquera - Cundinamarca",
          "Mosquera - Nariño",
          "Motavita - Boyacá",
          "Moñitos - Córdoba",
          "Murillo - Tolima",
          "Murindó - Antioquia",
          "Mutatá - Antioquia",
          "Mutiscua - Norte de Santander",
          "Muzo - Boyacá",
          "Málaga - Santander",
          "Nariño - Antioquia",
          "Nariño - Cundinamarca",
          "Nariño - Nariño",
          "Natagaima - Tolima",
          "Nechí - Antioquia",
          "Necoclí - Antioquia",
          "Neira - Caldas",
          "Neiva - Huila",
          "Nemocón - Cundinamarca",
          "Nilo - Cundinamarca",
          "Nimaima - Cundinamarca",
          "Nobsa - Boyacá",
          "Nocaima - Cundinamarca",
          "Norcasia - Caldas",
          "Norosí - Bolívar",
          "Nueva Granada - Magdalena",
          "Nuevo Colón - Boyacá",
          "Nunchía - Casanare",
          "Nuquí - Chocó",
          "Nátaga - Huila",
          "Nóvita - Chocó",
          "Obando - Valle del Cauca",
          "Ocamonte - Santander",
          "Ocaña - Norte de Santander",
          "Oiba - Santander",
          "Oicatá - Boyacá",
          "Olaya - Antioquia",
          "Olaya Herrera - Nariño",
          "Onzaga - Santander",
          "Oporapa - Huila",
          "Orito - Putumayo",
          "Orocué - Casanare",
          "Ortega - Tolima",
          "Ospina - Nariño",
          "Otanche - Boyacá",
          "Ovejas - Sucre",
          "Pachavita - Boyacá",
          "Pacho - Cundinamarca",
          "Pacoa - Vaupés",
          "Padilla - Cauca",
          "Paicol - Huila",
          "Pailitas - Cesar",
          "Paime - Cundinamarca",
          "Paipa - Boyacá",
          "Pajarito - Boyacá",
          "Palermo - Huila",
          "Palestina - Caldas",
          "Palestina - Huila",
          "Palmar - Santander",
          "Palmar de Varela - Atlántico",
          "Palmas del Socorro - Santander",
          "Palmira - Valle del Cauca",
          "Palmito - Sucre",
          "Palocabildo - Tolima",
          "Pamplona - Norte de Santander",
          "Pamplonita - Norte de Santander",
          "Pana Pana - Guainía",
          "Pandi - Cundinamarca",
          "Panqueba - Boyacá",
          "Papunaua - Vaupés",
          "Paratebueno - Cundinamarca",
          "Pasca - Cundinamarca",
          "Pasto - Nariño",
          "Patía - Cauca",
          "Pauna - Boyacá",
          "Paya - Boyacá",
          "Paz de Ariporo - Casanare",
          "Paz de Río - Boyacá",
          "Pedraza - Magdalena",
          "Pelaya - Cesar",
          "Pensilvania - Caldas",
          "Peque - Antioquia",
          "Pereira - Risaralda",
          "Pesca - Boyacá",
          "Peñol - Antioquia",
          "Piamonte - Cauca",
          "Piedecuesta - Santander",
          "Piedras - Tolima",
          "Piendamó - Cauca",
          "Pijao - Quindío",
          "Pijiño del Carmen - Magdalena",
          "Pinchote - Santander",
          "Pinillos - Bolívar",
          "Piojó - Atlántico",
          "Pisba - Boyacá",
          "Pital - Huila",
          "Pitalito - Huila",
          "Pivijay - Magdalena",
          "Planadas - Tolima",
          "Planeta Rica - Córdoba",
          "Plato - Magdalena",
          "Policarpa - Nariño",
          "Polonuevo - Atlántico",
          "Ponedera - Atlántico",
          "Popayán - Cauca",
          "Pore - Casanare",
          "Potosí - Nariño",
          "Pradera - Valle del Cauca",
          "Prado - Tolima",
          "Providencia - Nariño",
          "Pueblo Bello - Cesar",
          "Pueblo Nuevo - Córdoba",
          "Pueblo Rico - Risaralda",
          "Pueblo Viejo - Magdalena",
          "Pueblorrico - Antioquia",
          "Puente Nacional - Santander",
          "Puerres - Nariño",
          "Puerto Alegría - Amazonas",
          "Puerto Arica - Amazonas",
          "Puerto Asís - Putumayo",
          "Puerto Berrío - Antioquia",
          "Puerto Boyacá - Boyacá",
          "Puerto Caicedo - Putumayo",
          "Puerto Carreño - Vichada",
          "Puerto Colombia - Atlántico",
          "Puerto Colombia - Guainía",
          "Puerto Concordia - Meta",
          "Puerto Escondido - Córdoba",
          "Puerto Gaitán - Meta",
          "Puerto Guzmán - Putumayo",
          "Puerto Libertador - Córdoba",
          "Puerto Lleras - Meta",
          "Puerto López - Meta",
          "Puerto Nare - Antioquia",
          "Puerto Nariño - Amazonas",
          "Puerto Parra - Santander",
          "Puerto Rico - Caquetá",
          "Puerto Rico - Meta",
          "Puerto Rondón - Arauca",
          "Puerto Salgar - Cundinamarca",
          "Puerto Santander - Amazonas",
          "Puerto Santander - Norte de Santander",
          "Puerto Tejada - Cauca",
          "Puerto Triunfo - Antioquia",
          "Puerto Wilches - Santander",
          "Pulí - Cundinamarca",
          "Pupiales - Nariño",
          "Puracé - Cauca",
          "Purificación - Tolima",
          "Purísima - Córdoba",
          "Pácora - Caldas",
          "Páez - Boyacá",
          "Páez - Cauca",
          "Páramo - Santander",
          "Quebradanegra - Cundinamarca",
          "Quetame - Cundinamarca",
          "Quibdó - Chocó",
          "Quimbaya - Quindío",
          "Quinchía - Risaralda",
          "Quipile - Cundinamarca",
          "Quípama - Boyacá",
          "Ragonvalia - Norte de Santander",
          "Ramiriquí - Boyacá",
          "Recetor - Casanare",
          "Regidor - Bolívar",
          "Remedios - Antioquia",
          "Remolino - Magdalena",
          "Repelón - Atlántico",
          "Restrepo - Meta",
          "Restrepo - Valle del Cauca",
          "Retiro - Antioquia",
          "Ricaurte - Cundinamarca",
          "Ricaurte - Nariño",
          "Rio Blanco - Tolima",
          "Riofrío - Valle del Cauca",
          "Riohacha - La Guajira",
          "Rionegro - Antioquia",
          "Rionegro - Santander",
          "Riosucio - Caldas",
          "Riosucio - Chocó",
          "Risaralda - Caldas",
          "Rivera - Huila",
          "Roberto Payán - Nariño",
          "Roldanillo - Valle del Cauca",
          "Roncesvalles - Tolima",
          "Rondón - Boyacá",
          "Rosas - Cauca",
          "Rovira - Tolima",
          "Ráquira - Boyacá",
          "Río de Oro - Cesar",
          "Río Iro - Chocó",
          "Río Quito - Chocó",
          "Río Viejo - Bolívar",
          "Sabana de Torres - Santander",
          "Sabanagrande - Atlántico",
          "Sabanalarga - Antioquia",
          "Sabanalarga - Atlántico",
          "Sabanalarga - Casanare",
          "Sabanas de San Angel - Magdalena",
          "Sabaneta - Antioquia",
          "Saboyá - Boyacá",
          "Sahagún - Córdoba",
          "Saladoblanco - Huila",
          "Salamina - Caldas",
          "Salamina - Magdalena",
          "Salazar - Norte de Santander",
          "Saldaña - Tolima",
          "Salento - Quindío",
          "Salgar - Antioquia",
          "Samacá - Boyacá",
          "Samaniego - Nariño",
          "Samaná - Caldas",
          "Sampués - Sucre",
          "San Agustín - Huila",
          "San Alberto - Cesar",
          "San Andrés - Santander",
          "San Andrés de Cuerquía - Antioquia",
          "San Andrés de Tumaco - Nariño",
          "San Andrés Sotavento - Córdoba",
          "San Antero - Córdoba",
          "San Antonio - Tolima",
          "San Antonio del Tequendama - Cundinamarca",
          "San Benito - Santander",
          "San Benito Abad - Sucre",
          "San Bernardo - Cundinamarca",
          "San Bernardo - Nariño",
          "San Bernardo del Viento - Córdoba",
          "San Calixto - Norte de Santander",
          "San Carlos - Antioquia",
          "San Carlos - Córdoba",
          "San Carlos de Guaroa - Meta",
          "San Cayetano - Cundinamarca",
          "San Cayetano - Norte de Santander",
          "San Cristóbal - Bolívar",
          "San Diego - Cesar",
          "San Eduardo - Boyacá",
          "San Estanislao - Bolívar",
          "San Felipe - Guainía",
          "San Fernando - Bolívar",
          "San Francisco - Antioquia",
          "San Francisco - Cundinamarca",
          "San Francisco - Putumayo",
          "San Gil - Santander",
          "San Jacinto - Bolívar",
          "San Jacinto del Cauca - Bolívar",
          "San Jerónimo - Antioquia",
          "San Joaquín - Santander",
          "San José - Caldas",
          "San José de la Montaña - Antioquia",
          "San José de Miranda - Santander",
          "San José de Pare - Boyacá",
          "San José de Uré - Córdoba",
          "San José del Fragua - Caquetá",
          "San José del Guaviare - Guaviare",
          "San José del Palmar - Chocó",
          "San Juan de Arama - Meta",
          "San Juan de Betulia - Sucre",
          "San Juan de Río Seco - Cundinamarca",
          "San Juan de Urabá - Antioquia",
          "San Juan del Cesar - La Guajira",
          "San Juan Nepomuceno - Bolívar",
          "San Juanito - Meta",
          "San Lorenzo - Nariño",
          "San Luis - Antioquia",
          "San Luis - Tolima",
          "San Luis de Gaceno - Boyacá",
          "San Luis de Gaceno - Casanare",
          "San Luis de Sincé - Sucre",
          "San Marcos - Sucre",
          "San Martín - Cesar",
          "San Martín - Meta",
          "San Martín de Loba - Bolívar",
          "San Mateo - Boyacá",
          "San Miguel - Putumayo",
          "San Miguel - Santander",
          "San Miguel de Sema - Boyacá",
          "San Onofre - Sucre",
          "San Pablo - Nariño",
          "San Pablo de Borbur - Bolívar",
          "San Pablo de Borbur - Boyacá",
          "San Pedro - Antioquia",
          "San Pedro - Sucre",
          "San Pedro - Valle del Cauca",
          "San Pedro de Cartago - Nariño",
          "San Pedro de Uraba - Antioquia",
          "San Pelayo - Córdoba",
          "San Rafael - Antioquia",
          "San Roque - Antioquia",
          "San Sebastián - Cauca",
          "San Sebastián de Buenavista - Magdalena",
          "San Vicente - Antioquia",
          "San Vicente de Chucurí - Santander",
          "San Vicente del Caguán - Caquetá",
          "San Zenón - Magdalena",
          "Sandoná - Nariño",
          "Santa Ana - Magdalena",
          "Santa Bárbara - Antioquia",
          "Santa Bárbara - Nariño",
          "Santa Bárbara - Santander",
          "Santa Bárbara de Pinto - Magdalena",
          "Santa Catalina - Bolívar",
          "Santa Helena del Opón - Santander",
          "Santa Isabel - Tolima",
          "Santa Lucía - Atlántico",
          "Santa Marta - Magdalena",
          "Santa María - Boyacá",
          "Santa María - Huila",
          "Santa Rosa - Bolívar",
          "Santa Rosa - Cauca",
          "Santa Rosa de Cabal - Risaralda",
          "Santa Rosa de Osos - Antioquia",
          "Santa Rosa de Viterbo - Boyacá",
          "Santa Rosa del Sur - Bolívar",
          "Santa Rosalía - Vichada",
          "Santa Sofía - Boyacá",
          "Santacruz - Nariño",
          "Santafé de Antioquia - Antioquia",
          "Santana - Boyacá",
          "Santander de Quilichao - Cauca",
          "Santiago - Norte de Santander",
          "Santiago - Putumayo",
          "Santiago de Tolú - Sucre",
          "Santo Domingo - Antioquia",
          "Santo Tomás - Atlántico",
          "Santuario - Risaralda",
          "Sapuyes - Nariño",
          "Saravena - Arauca",
          "Sardinata - Norte de Santander",
          "Sasaima - Cundinamarca",
          "Sativanorte - Boyacá",
          "Sativasur - Boyacá",
          "Segovia - Antioquia",
          "Sesquilé - Cundinamarca",
          "Sevilla - Valle del Cauca",
          "Siachoque - Boyacá",
          "Sibaté - Cundinamarca",
          "Sibundoy - Putumayo",
          "Silos - Norte de Santander",
          "Silvania - Cundinamarca",
          "Silvia - Cauca",
          "Simacota - Santander",
          "Simijaca - Cundinamarca",
          "Simití - Bolívar",
          "Sincelejo - Sucre",
          "Sipí - Chocó",
          "Sitionuevo - Magdalena",
          "Soacha - Cundinamarca",
          "Soatá - Boyacá",
          "Socha - Boyacá",
          "Socorro - Santander",
          "Socotá - Boyacá",
          "Sogamoso - Boyacá",
          "Solano - Caquetá",
          "Soledad - Atlántico",
          "Solita - Caquetá",
          "Somondoco - Boyacá",
          "Sonsón - Antioquia",
          "Sopetrán - Antioquia",
          "Soplaviento - Bolívar",
          "Sopó - Cundinamarca",
          "Sora - Boyacá",
          "Soracá - Boyacá",
          "Sotaquirá - Boyacá",
          "Sotara - Cauca",
          "Suaita - Santander",
          "Suan - Atlántico",
          "Suaza - Huila",
          "Subachoque - Cundinamarca",
          "Sucre - Cauca",
          "Sucre - Santander",
          "Sucre - Sucre",
          "Suesca - Cundinamarca",
          "Supatá - Cundinamarca",
          "Supía - Caldas",
          "Suratá - Santander",
          "Susa - Cundinamarca",
          "Susacón - Boyacá",
          "Sutamarchán - Boyacá",
          "Sutatausa - Cundinamarca",
          "Sutatenza - Boyacá",
          "Suárez - Cauca",
          "Suárez - Tolima",
          "Sácama - Casanare",
          "Sáchica - Boyacá",
          "Tabio - Cundinamarca",
          "Tadó - Chocó",
          "Talaigua Nuevo - Bolívar",
          "Tamalameque - Cesar",
          "Tame - Arauca",
          "Taminango - Nariño",
          "Tangua - Nariño",
          "Taraira - Vaupés",
          "Tarapacá - Amazonas",
          "Tarazá - Antioquia",
          "Tarqui - Huila",
          "Tarso - Antioquia",
          "Tasco - Boyacá",
          "Tauramena - Casanare",
          "Tausa - Cundinamarca",
          "Tello - Huila",
          "Tena - Cundinamarca",
          "Tenerife - Magdalena",
          "Tenjo - Cundinamarca",
          "Tenza - Boyacá",
          "Teorama - Norte de Santander",
          "Teruel - Huila",
          "Tesalia - Huila",
          "Tibacuy - Cundinamarca",
          "Tibaná - Boyacá",
          "Tibasosa - Boyacá",
          "Tibirita - Cundinamarca",
          "Tibú - Norte de Santander",
          "Tierralta - Córdoba",
          "Timaná - Huila",
          "Timbiquí - Cauca",
          "Timbío - Cauca",
          "Tinjacá - Boyacá",
          "Tipacoque - Boyacá",
          "Tiquisio - Bolívar",
          "Titiribí - Antioquia",
          "Toca - Boyacá",
          "Tocaima - Cundinamarca",
          "Tocancipá - Cundinamarca",
          "Togüí - Boyacá",
          "Toledo - Antioquia",
          "Toledo - Norte de Santander",
          "Tolú Viejo - Sucre",
          "Tona - Santander",
          "Topaipí - Cundinamarca",
          "Toribio - Cauca",
          "Toro - Valle del Cauca",
          "Tota - Boyacá",
          "Totoró - Cauca",
          "Trinidad - Casanare",
          "Trujillo - Valle del Cauca",
          "Tubará - Atlántico",
          "Tuchín - Córdoba",
          "Tuluá - Valle del Cauca",
          "Tunja - Boyacá",
          "Tununguá - Boyacá",
          "Turbaco - Bolívar",
          "Turbaná - Bolívar",
          "Turbo - Antioquia",
          "Turmequé - Boyacá",
          "Tuta - Boyacá",
          "Tutazá - Boyacá",
          "Támara - Casanare",
          "Támesis - Antioquia",
          "Tópaga - Boyacá",
          "Túquerres - Nariño",
          "Ubalá - Cundinamarca",
          "Ubaque - Cundinamarca",
          "Ulloa - Valle del Cauca",
          "Umbita - Boyacá",
          "Une - Cundinamarca",
          "Unguía - Chocó",
          "Unión Panamericana - Chocó",
          "Uramita - Antioquia",
          "Uribe - Meta",
          "Uribia - La Guajira",
          "Urrao - Antioquia",
          "Urumita - La Guajira",
          "Usiacurí - Atlántico",
          "Valdivia - Antioquia",
          "Valencia - Córdoba",
          "Valle de Guamez - Putumayo",
          "Valle de San José - Santander",
          "Valle de San Juan - Tolima",
          "Valledupar - Cesar",
          "Valparaíso - Antioquia",
          "Valparaíso - Caquetá",
          "Vegachí - Antioquia",
          "Venadillo - Tolima",
          "Venecia - Antioquia",
          "Venecia - Cundinamarca",
          "Ventaquemada - Boyacá",
          "Vergara - Cundinamarca",
          "Versalles - Valle del Cauca",
          "Vetas - Santander",
          "Vianí - Cundinamarca",
          "Victoria - Caldas",
          "Vigía del Fuerte - Antioquia",
          "Vijes - Valle del Cauca",
          "Villa Caro - Norte de Santander",
          "Villa de Leyva - Boyacá",
          "Villa de San Diego de Ubate - Cundinamarca",
          "Villa del Rosario - Norte de Santander",
          "Villa fatima - Vaupés",
          "Villa Rica - Cauca",
          "Villagarzón - Putumayo",
          "Villagómez - Cundinamarca",
          "Villahermosa - Tolima",
          "Villamaría - Caldas",
          "Villanueva - Bolívar",
          "Villanueva - Casanare",
          "Villanueva - La Guajira",
          "Villanueva - Santander",
          "Villapinzón - Cundinamarca",
          "Villarrica - Tolima",
          "Villavicencio - Meta",
          "Villavieja - Huila",
          "Villeta - Cundinamarca",
          "Viotá - Cundinamarca",
          "Viracachá - Boyacá",
          "Vista Hermosa - Meta",
          "Viterbo - Caldas",
          "Vélez - Santander",
          "Yacopí - Cundinamarca",
          "Yacuanquer - Nariño",
          "Yaguará - Huila",
          "Yalí - Antioquia",
          "Yarumal - Antioquia",
          "Yavaraté - Vaupés",
          "Yolombó - Antioquia",
          "Yondó - Antioquia",
          "Yopal - Casanare",
          "Yotoco - Valle del Cauca",
          "Yumbo - Valle del Cauca",
          "Zambrano - Bolívar",
          "Zapatoca - Santander",
          "Zapayán - Magdalena",
          "Zaragoza - Antioquia",
          "Zarzal - Valle del Cauca",
          "Zetaquira - Boyacá",
          "Zipacón - Cundinamarca",
          "Zipaquirá - Cundinamarca",
          "Zona Bananera - Magdalena",
          "Útica - Cundinamarca");
}
